### ISSUE TITLE
[Enhancement] Under Windows, use NFTS Journal to access informations

### ISSUE THREAD

**Issue by jacekmusial** [gmethvin/directory-watcher#17]
When on Windows, and NTFS partition, I believe we could use NTFS USN journal. Program called [Everything](https://www.voidtools.com/support/everything/) have it implemented and it is blazing fast.

There are the open-source implementations of this:
https://sourceforge.net/projects/ntfs-search/
https://github.com/ChrisS85/FastFileSearch

Community, what do you think?
Personally, I'm using Everything every day (:D), thus am thinking it could of some use to this project.

**Comment by gmethvin** [comment]
@jacekmusial how exactly do you see this being used? The main thing directory-watcher needs to do is notify when a change has happened within a watched directory.
