### ISSUE TITLE
[JAVA] Multiple copy/delete operations do not emit 'CREATE' events afterwards

### ISSUE THREAD

**Issue by mangum99** [gmethvin/directory-watcher#35]
Hi,

There is an issue on Windows10 (but probably it will be also reproducable in other operating systems). 
Steps to reproduce:
- start watcher with file hashing
- copy from outside a folder containing some files
- we will get correctly corresponding CREATE and/or MODIFY events
- then delete the copied folder
- we will get one 'DELETE' event (saying that the folder was deleted - but no information about files)
- then copy again the same folder with the same files 
- we will get only event regarding the copied folder but no events that the files were also created/modified

This probably has something to do with the "pathHashes"-variable, because when folder is being deleted only the hash of this folder gets deleted but its children remain in the "pathHashes". So if we copy again same files which are inside of some folder, events will be skipped.

If fileHashing is turned off then this use case works.

**Comment by gmethvin** [comment]
What version is this on?

I think we probably need to apply the same logic to deletion as we do for creation events. In other words, remove the hashes from the map for all files in the directory.

Any interest in submitting a pull request to fix it?

**Comment by mangum99** [comment]
It was on the version 0.9.3. I'll take a look and try to provide some solution for it.
