### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ignasi35** [gmethvin/directory-watcher#46]
Hi @gmethvin, it's been a few months since the last release and we'd like to use some of the improvements added recently.

Is there anything we can help you with to get a new release?

**Comment by gmethvin** [comment]
Sure, no problem.

**Comment by gmethvin** [comment]
Released `0.9.7`

**Comment by marcospereira** [comment]
Thanks, @gmethvin. I think we can close this.

**Comment by ignasi35** [comment]
Thanks @gmethvin 🎉
