### ISSUE TITLE
DirectoryWatcher.watch() throws ClosedWatchServiceException when Watcher is closed

### ISSUE THREAD

**Issue by kwin** [gmethvin/directory-watcher#79]
According to the javadoc of `DirectoryWatcher.watch()` (https://github.com/gmethvin/directory-watcher/blob/9eac61c0819db9ce67ac11e2b2c3927621c0fb8a/core/src/main/java/io/methvin/watcher/DirectoryWatcher.java#L224) it

> Block(s) until either the listener stops watching or the DirectoryWatcher is closed.

Actually the methods throws a `java.nio.file.ClosedWatchServiceException` in case the watcher has been closed.
```
 java.nio.file.ClosedWatchServiceException
	at io.methvin.watchservice.AbstractWatchService.check(AbstractWatchService.java:94)
	at io.methvin.watchservice.AbstractWatchService.take(AbstractWatchService.java:86)
	at io.methvin.watchservice.MacOSXListeningWatchService.take(MacOSXListeningWatchService.java:38)
	at io.methvin.watcher.DirectoryWatcher.watch(DirectoryWatcher.java:231)
....
```

Either this should be clarified in the javadoc or closing the watcher should just unblock `watch` without throwing an exception

**Comment by gmethvin** [comment]
I think it makes more sense to throw immediately if the watcher is closed. What do you think? Happy to accept a pull request to clarify docs.

**Comment by kwin** [comment]
IMHO just returning without throwing makes more sense. Otherwise I think watch can never return ordinarily. Exceptions should IMHO not be used for regular flow control and closing the watcher is IMHO the only means to end a dedicated watcher thread.

**Comment by gmethvin** [comment]
ok, I think I understand now. I agree that if `watch()` is currently watching and the directory watcher is closed, we should return normally. But if you call `watch()` on a watcher that is _already_ closed, then it should throw, since calling `watch` on a closed watcher doesn't make sense.

**Comment by gmethvin** [comment]
see #80
