### ISSUE TITLE
onUnknownEvent in trait Monitor of type (event: java.nio.file.WatchEvent[_])Unit is not defined

### ISSUE THREAD

**Issue by rogertangcn** [gmethvin/directory-watcher#8]
The cause of the problem is because in Better files, `File.Monitor.onUnknownEvent()` method has removed `count` parameter in [this commit](https://github.com/pathikrit/better-files/commit/8cc66d0e8ac6517597eeb1db1814903f2256b805#diff-44cb99a44aaa9dc8fe0c60d9ed140e35).

**Comment by gmethvin** [comment]
Interesting. I thought better-files followed semver so I'm surprised they broke this in 3.4.0. The new API makes more sense though. The fix here is just to update to the latest better-files and update our code to conform to the new interface.

@rogertangcn interested in submitting a pull request?

**Comment by rogertangcn** [comment]
Yeah, I can try.

**Comment by gmethvin** [comment]
Great, thanks!

**Comment by gmethvin** [comment]
Pretty sure all that's required is:
 - Change https://github.com/gmethvin/directory-watcher/blob/master/better-files/src/main/scala/io/methvin/better/files/RecursiveFileMonitor.scala#L63 to remove the count parameter.
 - Stop passing count at https://github.com/gmethvin/directory-watcher/blob/master/better-files/src/main/scala/io/methvin/better/files/RecursiveFileMonitor.scala#L34 (better-files considers overflow an "unknown" event).
 - Upgrade better-files at https://github.com/gmethvin/directory-watcher/blob/master/build.sbt#L40 to whatever the latest version is.

**Comment by rogertangcn** [comment]
I get this error when pushing up my branch. I'm using ssh pushing the code up. Did i miss anything?

`ERROR: Permission to gmethvin/directory-watcher.git denied to rogertangcn.`

**Comment by gmethvin** [comment]
Fixed by #9

**Comment by gmethvin** [comment]
This is fixed in version 0.5.0
