### ISSUE TITLE
Access denied stops walking file tree

### ISSUE THREAD

**Issue by zenios** [gmethvin/directory-watcher#81]
Hi

When walking a folder using Files.walkFileTree if a file / folder cannot be accessed an exception is thrown and the whole walking is finished.

It might be good to handle such cases by overriding visitFileFailed and continue instead of breaking

**Comment by gmethvin** [comment]
That’s definitely not ideal. What do you think the right behavior is? I wonder if we should just always ignore the error, of if we should notify the user somehow.

**Comment by zenios** [comment]
When i first saw these issue i though it would be nice for the consumer to pass a function that will be invoked on access denied or in general other. After giving it some though i am not sure whether someone would want to do something with the solutio

**Comment by zenios** [comment]
The default should be Continue and at the same time give the option to the
user to pass a handler on construction something like the following

DirectoryWatcher.builder().onVisitFileFailed(e -> FileVisitResult.TERMINATE)

**Comment by gmethvin** [comment]
That sounds reasonable. Do you want to send a PR?

**Comment by zenios** [comment]
Sure will try to work over the weekend.not sure how a test case can be
written though for such cases

**Comment by zenios** [comment]
Hey

I had a look over the code. So the issue happens at recursiveVisitFiles. That method is being called plenty of times
1. Directory created while watching
2. Directory watcher init to calculate hashes
3. Directory watcher init to register folders
4. Some more times inside MacOSXListeningWatchService which didn't check to see exactly what it does

Since the method might be called multiple times from different functions for same paths we need a consistent result. We cant let the consumer decide ( We want to avoid situations in which when calculating hashes the consumer returns SKIP_SIBLINGS and on folder registration the consumer returns TERMINATE ) 

Based on the above our 3 remaining options are
- TERMINATE (Why shall we terminate visiting? We are directory watcher library. We should keep scanning if possible)
- CONTINUE (SKIP_SUBTREE on visitFileFailed behaves exactly like CONTINUE)
- SKIP_SIBLINGS

Based on this small analysis i think that we should enforce CONTINUE and done with it.

As for notifying the user, since the user has no control over what happens there is no point (Nothing the user can do except logging and for that case we can use the already injected logger) 

Looking forward to your comments

**Comment by gmethvin** [comment]
I agree CONTINUE is probably the most useful behavior in most cases. It would be useful to at least log a warning there though.

I'm not convinced that a notification mechanism isn't useful though. What if the program using the watcher wants to ask the end user to fix their permissions?

**Comment by gmethvin** [comment]
I do agree though that it's kind of a pain to go through and add a callback to every single case where we use the file visitor. Why don't we start with just continue and log, then we can look at incremental improvements from there?
